title: Your Site Title
description: A brief description
baseurl: "https://akoslowski.gihub.io"
permalink: pretty
remote_theme: ronv/sidey
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
